export { default as Home } from './Home';
export { default as Menu } from './Menu';
export { default as User } from './User';
export { default as Setting } from './Setting';
export { default as File } from './File';
export { default as Post } from './Post';
export { default as Banner } from './Banner';
export { default as Comment } from './Comment';
export { default as Catrgory } from './Category';
